### ISSUE TITLE
Overwrite functions based on which UniverseId / GameId / PlaceId is currently available.

### ISSUE THREAD

**Issue by LittleDyingDuck** [paygammy/aim-assistant#1]
Instead of using "if gamename then player = phantomforces.characters[idx] elseif ... end" for individually getting characters, try doing something like a custom get_character function, so you would overwrite it depending on what game is loaded, or universal.

i.e
```
if game.PlaceId == phantomforceplaceid then
  util.get_character = function(player) return bodyparts[player].Character end
  util.get_alive = function(player) if player == LocalPlayer then return char.alive else return hud:getplayerhealth(player)>0 end end
end ```

**Comment by paygammy** [comment]
This has been resolved.
It is now included in the script.
